// <auto-generated />
using System;
using FinNex.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinNex.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211190434_SenedModuleInit")]
    partial class SenedModuleInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinNex.Domain.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FinNex.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("QeydiyyatTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuxHesab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SwiftBic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Banklar");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.BankHesabi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ValyutaId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ValyutaId");

                    b.ToTable("BankHesablari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Voen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.MusteriHesabi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ValyutaId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("ValyutaId");

                    b.ToTable("MusteriHesablari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.OdenisTapsirigi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlanBankId")
                        .HasColumnType("int");

                    b.Property<int>("AlanHesabId")
                        .HasColumnType("int");

                    b.Property<int>("AlanMusteriId")
                        .HasColumnType("int");

                    b.Property<string>("BudceSeviyyesininKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BudceTesnifatininKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElaveInformasiya")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Mebleg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MeblegYazi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OduyenBankId")
                        .HasColumnType("int");

                    b.Property<int>("OduyenHesabId")
                        .HasColumnType("int");

                    b.Property<int>("OduyenMusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.Property<string>("Teyinat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValyutaId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlanBankId");

                    b.HasIndex("AlanHesabId");

                    b.HasIndex("AlanMusteriId");

                    b.HasIndex("OduyenBankId");

                    b.HasIndex("OduyenHesabId");

                    b.HasIndex("OduyenMusteriId");

                    b.HasIndex("ValyutaId");

                    b.ToTable("OdenisTapsiriqlari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.OdenisTapsirigiNomresi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Il")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SonNomre")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OdenisTapsirigiNomreleri");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SenedId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenedId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Sened", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcarSoz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Basliq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mexfilik")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenedNovuId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SobeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenedNovuId");

                    b.HasIndex("SobeId");

                    b.ToTable("Senedler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<int>("PrincipalId")
                        .HasColumnType("int");

                    b.Property<int>("PrincipalType")
                        .HasColumnType("int");

                    b.Property<int>("SenedId")
                        .HasColumnType("int");

                    b.Property<int?>("SenedId1")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenedId");

                    b.HasIndex("SenedId1");

                    b.ToTable("SenedAccessler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedFayl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktivVersiya")
                        .HasColumnType("bit");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OlcuBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenedId")
                        .HasColumnType("int");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersiyaNo")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.Property<string>("Yol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SenedId", "VersiyaNo")
                        .IsUnique();

                    b.ToTable("SenedFayllar");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedNovu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SobeId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SobeId");

                    b.ToTable("SenedNovleri");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedTagMap", b =>
                {
                    b.Property<int>("SenedId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("SenedId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("SenedTagMaps");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Sobe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sobeler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tagler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.Structure.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciqlama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.Valyuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Valyutalar");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.BankHesabi", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Bank", "Bank")
                        .WithMany("BankHesablari")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.Valyuta", "Valyuta")
                        .WithMany()
                        .HasForeignKey("ValyutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Valyuta");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.MusteriHesabi", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Musteri", "Musteri")
                        .WithMany("MusteriHesablari")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.Valyuta", "Valyuta")
                        .WithMany()
                        .HasForeignKey("ValyutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Valyuta");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.OdenisTapsirigi", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Bank", "AlanBank")
                        .WithMany()
                        .HasForeignKey("AlanBankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.MusteriHesabi", "AlanHesab")
                        .WithMany()
                        .HasForeignKey("AlanHesabId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Musteri", "AlanMusteri")
                        .WithMany()
                        .HasForeignKey("AlanMusteriId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Bank", "OduyenBank")
                        .WithMany()
                        .HasForeignKey("OduyenBankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.MusteriHesabi", "OduyenHesab")
                        .WithMany()
                        .HasForeignKey("OduyenHesabId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Musteri", "OduyenMusteri")
                        .WithMany()
                        .HasForeignKey("OduyenMusteriId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.Valyuta", "Valyuta")
                        .WithMany()
                        .HasForeignKey("ValyutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlanBank");

                    b.Navigation("AlanHesab");

                    b.Navigation("AlanMusteri");

                    b.Navigation("OduyenBank");

                    b.Navigation("OduyenHesab");

                    b.Navigation("OduyenMusteri");

                    b.Navigation("Valyuta");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.AuditLog", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sened", "Sened")
                        .WithMany()
                        .HasForeignKey("SenedId");

                    b.Navigation("Sened");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Sened", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.SenedNovu", "SenedNovu")
                        .WithMany()
                        .HasForeignKey("SenedNovuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sobe", "Sobe")
                        .WithMany("Senedler")
                        .HasForeignKey("SobeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SenedNovu");

                    b.Navigation("Sobe");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedAccess", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sened", "Sened")
                        .WithMany()
                        .HasForeignKey("SenedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sened", null)
                        .WithMany("Accessler")
                        .HasForeignKey("SenedId1");

                    b.Navigation("Sened");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedFayl", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sened", "Sened")
                        .WithMany("Fayllar")
                        .HasForeignKey("SenedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sened");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedNovu", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sobe", "Sobe")
                        .WithMany("SenedNovleri")
                        .HasForeignKey("SobeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sobe");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedTagMap", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sened", "Sened")
                        .WithMany("SenedTagMaps")
                        .HasForeignKey("SenedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Tag", "Tag")
                        .WithMany("SenedTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sened");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("FinNex.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FinNex.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FinNex.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("FinNex.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FinNex.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Bank", b =>
                {
                    b.Navigation("BankHesablari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Musteri", b =>
                {
                    b.Navigation("MusteriHesablari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Sened", b =>
                {
                    b.Navigation("Accessler");

                    b.Navigation("Fayllar");

                    b.Navigation("SenedTagMaps");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Sobe", b =>
                {
                    b.Navigation("SenedNovleri");

                    b.Navigation("Senedler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Tag", b =>
                {
                    b.Navigation("SenedTagMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
