// <auto-generated />
using System;
using FinNex.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinNex.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinNex.Domain.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FinNex.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("IsciId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("QeydiyyatTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.BayramGunu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HerIlTeyinOlunur")
                        .HasColumnType("bit");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BayramGunleri");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Davamiyyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CixisVaxti")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GirisVaxti")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsciId", "Tarix")
                        .IsUnique();

                    b.ToTable("Davamiyyetler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Icaze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BaslamaSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<int>("EvezEdenIsciId")
                        .HasColumnType("int");

                    b.Property<int?>("HrId")
                        .HasColumnType("int");

                    b.Property<bool?>("HrTesdiq")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HrTesdiqTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IcazeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImtinaSebebi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int?>("RehberId")
                        .HasColumnType("int");

                    b.Property<bool?>("RehberTesdiq")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RehberTesdiqTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sebeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SobeReisiId")
                        .HasColumnType("int");

                    b.Property<bool?>("SobeReisiTesdiq")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SobeReisiTesdiqTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvezEdenIsciId");

                    b.HasIndex("HrId");

                    b.HasIndex("IsciId");

                    b.HasIndex("RehberId");

                    b.HasIndex("SobeReisiId");

                    b.ToTable("Icazeler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Isci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("AtaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cins")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("IsdenAyrilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsheQebulTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeriyaNomre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique()
                        .HasFilter("[AppUserId] IS NOT NULL");

                    b.HasIndex("FIN")
                        .IsUnique();

                    b.ToTable("Isciler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.IsciMaasTarixcesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeyismeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmrinNomresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<decimal>("KohneMaas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("YeniMaas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.ToTable("IsciMaasTarixcesi");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.IsciMaliye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankHesabNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CariMaas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int>("MezuniyyetQaliqGunu")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SosialSigortaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsciId")
                        .IsUnique();

                    b.ToTable("IsciMaliye");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.IsciStrukturRolu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BaslamaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int>("RolTipi")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("IsciId");

                    b.ToTable("IsciStrukturRollari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.IsciTeyinat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BaslamaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<bool>("Esasdir")
                        .HasColumnType("bit");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("VezifeId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("IsciId");

                    b.HasIndex("VezifeId");

                    b.ToTable("IsciTeyinatlari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Maas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ay")
                        .HasColumnType("int");

                    b.Property<int>("Il")
                        .HasColumnType("int");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int?>("IsciId1")
                        .HasColumnType("int");

                    b.Property<decimal>("NetMebleg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsciId1");

                    b.HasIndex("IsciId", "Il", "Ay")
                        .IsUnique();

                    b.ToTable("Maaslar");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.MaasDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acıqlama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaasId")
                        .HasColumnType("int");

                    b.Property<int>("MaasNovuId")
                        .HasColumnType("int");

                    b.Property<decimal>("Mebleg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaasId");

                    b.HasIndex("MaasNovuId");

                    b.ToTable("MaasDetay");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.MaasNovu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<bool>("Gelirdir")
                        .HasColumnType("bit");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MaasNovu");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Mezuniyyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslamaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EvezEdenIsciId")
                        .HasColumnType("int");

                    b.Property<int?>("HrId")
                        .HasColumnType("int");

                    b.Property<bool?>("HrTesdiq")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HrTesdiqTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImtinaSebebi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsGunlerininSayi")
                        .HasColumnType("int");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int>("Nov")
                        .HasColumnType("int");

                    b.Property<string>("Qeyd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RehberId")
                        .HasColumnType("int");

                    b.Property<bool?>("RehberTesdiq")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RehberTesdiqTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SobeReisiId")
                        .HasColumnType("int");

                    b.Property<bool?>("SobeReisiTesdiq")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SobeReisiTesdiqTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvezEdenIsciId");

                    b.HasIndex("IsciId");

                    b.ToTable("Mezuniyyetler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.MezuniyyetBalans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Il")
                        .HasColumnType("int");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int>("IstifadeOlunanGun")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamGun")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsciId")
                        .IsUnique();

                    b.HasIndex("IsciId", "Il")
                        .IsUnique();

                    b.ToTable("MezuniyyetBalanslari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciqlama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Allowed")
                        .HasColumnType("bit");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Vezife", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<int>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tesvir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.HasIndex("DepartamentId");

                    b.ToTable("Vezifeler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuxHesab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SwiftBic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Banklar");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.BankHesabi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ValyutaId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ValyutaId");

                    b.ToTable("BankHesablari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Voen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.MusteriHesabi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ValyutaId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ValyutaId");

                    b.HasIndex("MusteriId", "Iban")
                        .IsUnique();

                    b.ToTable("MusteriHesablari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.OdenisTapsirigi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlanBankId")
                        .HasColumnType("int");

                    b.Property<int>("AlanHesabId")
                        .HasColumnType("int");

                    b.Property<int>("AlanMusteriId")
                        .HasColumnType("int");

                    b.Property<string>("BudceSeviyyesininKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BudceTesnifatininKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElaveInformasiya")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Mebleg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MeblegYazi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OduyenBankId")
                        .HasColumnType("int");

                    b.Property<int>("OduyenHesabId")
                        .HasColumnType("int");

                    b.Property<int>("OduyenMusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.Property<string>("Teyinat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValyutaId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlanBankId");

                    b.HasIndex("AlanHesabId");

                    b.HasIndex("AlanMusteriId");

                    b.HasIndex("OduyenBankId");

                    b.HasIndex("OduyenHesabId");

                    b.HasIndex("OduyenMusteriId");

                    b.HasIndex("ValyutaId");

                    b.ToTable("OdenisTapsiriqlari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.OdenisTapsirigiNomresi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Il")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SonNomre")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OdenisTapsirigiNomreleri");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SenedId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenedId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Sened", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcarSoz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Basliq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Mexfilik")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenedNovuId")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SenedNovuId");

                    b.ToTable("Senedler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<int>("PrincipalId")
                        .HasColumnType("int");

                    b.Property<int>("PrincipalType")
                        .HasColumnType("int");

                    b.Property<int>("SenedId")
                        .HasColumnType("int");

                    b.Property<int?>("SenedId1")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenedId");

                    b.HasIndex("SenedId1");

                    b.ToTable("SenedAccessler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedFayl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktivVersiya")
                        .HasColumnType("bit");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OlcuBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenedId")
                        .HasColumnType("int");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersiyaNo")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.Property<string>("Yol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SenedId", "VersiyaNo")
                        .IsUnique();

                    b.ToTable("SenedFayllar");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedNovu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("SenedNovleri");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedTagMap", b =>
                {
                    b.Property<int>("SenedId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("SenedId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("SenedTagMaps");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tagler");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.Structure.Departament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciqlama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.Structure.UserDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("Esasdir")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDepartments", (string)null);
                });

            modelBuilder.Entity("FinNex.Domain.Entities.Valyuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SilenIcraciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YaradanIcraciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YenilenmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YenileyenIcraciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Valyutalar");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Davamiyyet", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "Isci")
                        .WithMany()
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Icaze", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "EvezEdenIsci")
                        .WithMany()
                        .HasForeignKey("EvezEdenIsciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "HrTesdiqleyen")
                        .WithMany()
                        .HasForeignKey("HrId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "Isci")
                        .WithMany()
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "Rehber")
                        .WithMany()
                        .HasForeignKey("RehberId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "SobeReisi")
                        .WithMany()
                        .HasForeignKey("SobeReisiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EvezEdenIsci");

                    b.Navigation("HrTesdiqleyen");

                    b.Navigation("Isci");

                    b.Navigation("Rehber");

                    b.Navigation("SobeReisi");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Isci", b =>
                {
                    b.HasOne("FinNex.Domain.AppUser", "AppUser")
                        .WithOne("Isci")
                        .HasForeignKey("FinNex.Domain.Entities.HR.Isci", "AppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.IsciMaasTarixcesi", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "Isci")
                        .WithMany("MaasTarixcesi")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.IsciMaliye", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "Isci")
                        .WithOne("Maliye")
                        .HasForeignKey("FinNex.Domain.Entities.HR.IsciMaliye", "IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.IsciStrukturRolu", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.Structure.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "Isci")
                        .WithMany()
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Departament");

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.IsciTeyinat", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.Structure.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "Isci")
                        .WithMany("IsciTeyinatlari")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.HR.Vezife", "Vezife")
                        .WithMany()
                        .HasForeignKey("VezifeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Departament");

                    b.Navigation("Isci");

                    b.Navigation("Vezife");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Maas", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "Isci")
                        .WithMany()
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.HR.Isci", null)
                        .WithMany("Maaslar")
                        .HasForeignKey("IsciId1");

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.MaasDetay", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.HR.Maas", "Maas")
                        .WithMany("Detallar")
                        .HasForeignKey("MaasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.HR.MaasNovu", "MaasNovu")
                        .WithMany("MaasDetallari")
                        .HasForeignKey("MaasNovuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maas");

                    b.Navigation("MaasNovu");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Mezuniyyet", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "EvezEdenIsci")
                        .WithMany()
                        .HasForeignKey("EvezEdenIsciId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "Isci")
                        .WithMany()
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EvezEdenIsci");

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.MezuniyyetBalans", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.HR.Isci", "Isci")
                        .WithOne("MezuniyyetBalans")
                        .HasForeignKey("FinNex.Domain.Entities.HR.MezuniyyetBalans", "IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.UserPermission", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.HR.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Vezife", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.Structure.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.BankHesabi", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Bank", "Bank")
                        .WithMany("BankHesablari")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.Valyuta", "Valyuta")
                        .WithMany()
                        .HasForeignKey("ValyutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Valyuta");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.MusteriHesabi", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Musteri", "Musteri")
                        .WithMany("MusteriHesablari")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.Valyuta", "Valyuta")
                        .WithMany()
                        .HasForeignKey("ValyutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Valyuta");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.OdenisTapsirigi", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Bank", "AlanBank")
                        .WithMany()
                        .HasForeignKey("AlanBankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.MusteriHesabi", "AlanHesab")
                        .WithMany()
                        .HasForeignKey("AlanHesabId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Musteri", "AlanMusteri")
                        .WithMany()
                        .HasForeignKey("AlanMusteriId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Bank", "OduyenBank")
                        .WithMany()
                        .HasForeignKey("OduyenBankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.MusteriHesabi", "OduyenHesab")
                        .WithMany()
                        .HasForeignKey("OduyenHesabId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Musteri", "OduyenMusteri")
                        .WithMany()
                        .HasForeignKey("OduyenMusteriId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.Valyuta", "Valyuta")
                        .WithMany()
                        .HasForeignKey("ValyutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlanBank");

                    b.Navigation("AlanHesab");

                    b.Navigation("AlanMusteri");

                    b.Navigation("OduyenBank");

                    b.Navigation("OduyenHesab");

                    b.Navigation("OduyenMusteri");

                    b.Navigation("Valyuta");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.AuditLog", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sened", "Sened")
                        .WithMany()
                        .HasForeignKey("SenedId");

                    b.HasOne("FinNex.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sened");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Sened", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.Structure.Departament", "Department")
                        .WithMany("Senedler")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.SenedNovu", "SenedNovu")
                        .WithMany()
                        .HasForeignKey("SenedNovuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("SenedNovu");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedAccess", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sened", "Sened")
                        .WithMany()
                        .HasForeignKey("SenedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sened", null)
                        .WithMany("Accessler")
                        .HasForeignKey("SenedId1");

                    b.Navigation("Sened");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedFayl", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sened", "Sened")
                        .WithMany("Fayllar")
                        .HasForeignKey("SenedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sened");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedNovu", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.Structure.Departament", "Department")
                        .WithMany("SenedNovleri")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.SenedTagMap", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Sened", "Sened")
                        .WithMany("SenedTagMaps")
                        .HasForeignKey("SenedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.Entities.SenedDovriyyesi.Tag", "Tag")
                        .WithMany("SenedTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sened");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.Structure.UserDepartment", b =>
                {
                    b.HasOne("FinNex.Domain.Entities.Structure.Departament", "Department")
                        .WithMany("UserDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.AppUser", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("FinNex.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FinNex.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FinNex.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("FinNex.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinNex.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FinNex.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinNex.Domain.AppUser", b =>
                {
                    b.Navigation("Isci");

                    b.Navigation("UserDepartments");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Isci", b =>
                {
                    b.Navigation("IsciTeyinatlari");

                    b.Navigation("MaasTarixcesi");

                    b.Navigation("Maaslar");

                    b.Navigation("Maliye");

                    b.Navigation("MezuniyyetBalans");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.Maas", b =>
                {
                    b.Navigation("Detallar");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.HR.MaasNovu", b =>
                {
                    b.Navigation("MaasDetallari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Bank", b =>
                {
                    b.Navigation("BankHesablari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.PR_Odenis_Tapsirigi.Musteri", b =>
                {
                    b.Navigation("MusteriHesablari");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Sened", b =>
                {
                    b.Navigation("Accessler");

                    b.Navigation("Fayllar");

                    b.Navigation("SenedTagMaps");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.SenedDovriyyesi.Tag", b =>
                {
                    b.Navigation("SenedTagMaps");
                });

            modelBuilder.Entity("FinNex.Domain.Entities.Structure.Departament", b =>
                {
                    b.Navigation("SenedNovleri");

                    b.Navigation("Senedler");

                    b.Navigation("UserDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
